title: My Home
views:
  - path: default_view
    title: Home
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            entities:
              - entity: sensor.seeedstudio_mmwave_kit_hardware_model
                name: Hardware Model
              - entity: sensor.seeedstudio_mmwave_kit_hardware_version
                name: Hardware Version
              - entity: sensor.seeedstudio_mmwave_kit_heartbeat
                name: Heartbeat
              - entity: sensor.seeedstudio_mmwave_kit_initialization_status
                name: Initialization Status
              - entity: sensor.seeedstudio_mmwave_kit_product_id
                name: Product ID
              - entity: sensor.seeedstudio_mmwave_kit_product_model
                name: Product Model
            title: DEVICE Information
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: binary_sensor.seeedstudio_mmwave_kit_presence_information
                name: Presence Information
              - entity: sensor.seeedstudio_mmwave_kit_motion_information
                name: Motion Information
              - entity: sensor.seeedstudio_mmwave_kit_body_movement_parameter
                name: Body Movement Parameter
              - entity: sensor.seeedstudio_mmwave_kit_static_distance
                name: Static Distance
              - entity: sensor.seeedstudio_mmwave_kit_active_reporting_of_proximity
                name: Active Reporting Of Proximity
            title: Unsolicited Information